---
- name: 'add repository'
  apt_repository:
    repo: 'ppa:hda-me/nginx-stable'
    update_cache: no

- name: 'install'
  become: true
  apt:
    pkg: 'nginx'
    state: 'latest'


- name: 'create: /etc/nginx/nginx.conf'
  become: true
  template:
    src: '{{ nginx_conf }}'
    dest: '/etc/nginx/nginx.conf'

- file:
    path: /home/{{user}}/vhosts
    state: directory
    owner: '{{ user }}'
    mode: 0775

- file:
    path: /home/{{user}}/www
    state: directory
    owner: '{{ user }}'
    mode: 0775
