---
- name: 'add repository'
  become: true
  apt_repository:
    repo: 'ppa:ondrej/php'
    update_cache: yes
    
   
- name: 'install php7'
  become: true
  apt:
    pkg: 'php{{ php_version }},php{{ php_version }}-bz2,php{{ php_version }}-bcmath,php{{ php_version }}-cli,php{{ php_version }}-bcmath,php{{ php_version }}-cli,php{{ php_version }}-common,php{{ php_version }}-curl,php{{ php_version }}-dev,php{{ php_version }}-fpm,php{{ php_version }}-gd,php{{ php_version }}-gmp,php{{ php_version }}-intl,php{{ php_version }}-json,php{{ php_version }}-mbstring,php{{ php_version }}-mcrypt,php{{ php_version }}-mysql,php{{ php_version }}-opcache,php{{ php_version }}-readline,php{{ php_version }}-sqlite3,php{{ php_version }}-xml,php{{ php_version }}-zip,php{{ php_version }}-bcmath'
    state: 'latest'

